package update

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"bb_erp_echo/internal/shared/jsonstrict"

	"aead.dev/minisign"
	"golang.org/x/mod/semver"
)

const (
	// ClientUpdateProtocolVersion is the only supported client update wire
	// protocol. Older NSIS/Tauri and delta protocols are deliberately removed.
	ClientUpdateProtocolVersion = 1
	clientTargetWindowsX64      = "windows-x86_64"
	clientArtifactKindPortable  = "portable"
	clientArtifactFileName      = "bb_erp_client.exe"
	sha256HexLength             = 64
)

// SignedClientUpdateManifest is the exact on-disk client-update.json envelope.
// Payload contains base64-encoded strict JSON and Signature contains a base64
// encoded detached Minisign signature over the decoded payload bytes.
type SignedClientUpdateManifest struct {
	Payload   string `json:"payload"`
	Signature string `json:"signature"`
}

// ClientUpdatePayload is the signed portable Windows update description.
// The artifact filename is intentionally not configurable: the server only
// reads the fixed sibling client/bb_erp_client.exe path.
type ClientUpdatePayload struct {
	Version  string         `json:"version"`
	Target   string         `json:"target"`
	Artifact ClientArtifact `json:"artifact"`
}

// ClientArtifact describes the single complete executable protected by the
// signed payload. URL and local paths are never accepted from this payload.
type ClientArtifact struct {
	Kind      string `json:"kind"`
	Size      int64  `json:"size"`
	SHA256    string `json:"sha256"`
	Signature string `json:"signature"`
}

// ClientUpdatePlanArtifact is the API-safe artifact reference. DownloadPath
// is generated by the server from the verified digest and is never read from
// the signed input.
type ClientUpdatePlanArtifact struct {
	Kind         string `json:"kind"`
	Size         int64  `json:"size"`
	SHA256       string `json:"sha256"`
	Signature    string `json:"signature"`
	DownloadPath string `json:"download_path"`
}

// ClientUpdatePlan is returned by GET /api/v1/client-updates/check. It is a
// complete portable update plan; no installer mode, delta or external URL is
// supported.
type ClientUpdatePlan struct {
	ProtocolVersion int                      `json:"protocol_version"`
	CurrentVersion  string                   `json:"current_version"`
	LatestVersion   string                   `json:"latest_version"`
	Target          string                   `json:"target"`
	Strategy        string                   `json:"strategy"`
	DownloadSize    int64                    `json:"download_size"`
	SignedPayload   string                   `json:"signed_payload"`
	Signature       string                   `json:"signature"`
	Artifact        ClientUpdatePlanArtifact `json:"artifact"`
}

// SignedManifestVerifier validates a Minisign payload or file.
type SignedManifestVerifier interface {
	Verify(payload []byte, signature string) error
	VerifyFile(path, signature string) error
}

// MinisignVerifier uses the exact public key embedded in official clients.
type MinisignVerifier struct {
	public minisign.PublicKey
}

// NewMinisignVerifier parses a canonical Minisign public-key envelope. Tauri's
// generated key is itself commonly base64 encoded, so that representation is
// accepted after the direct textual form.
func NewMinisignVerifier(publicKey string) (*MinisignVerifier, error) {
	var key minisign.PublicKey
	keyText := []byte(strings.TrimSpace(publicKey))
	if len(keyText) == 0 {
		return nil, errors.New("minisign public key is empty")
	}
	if err := key.UnmarshalText(keyText); err != nil {
		decoded, decodeErr := base64.StdEncoding.DecodeString(string(keyText))
		if decodeErr != nil {
			return nil, fmt.Errorf("parse minisign public key: %w", err)
		}
		if decodedErr := key.UnmarshalText(decoded); decodedErr != nil {
			return nil, fmt.Errorf("parse minisign public key: %w", err)
		}
	}
	return &MinisignVerifier{public: key}, nil
}

// Verify validates a detached signature over payload.
func (v *MinisignVerifier) Verify(payload []byte, signature string) error {
	if v == nil {
		return errors.New("minisign verifier is not configured")
	}
	signatureText, err := decodeSignature(signature)
	if err != nil {
		return err
	}
	if !minisign.Verify(v.public, payload, signatureText) {
		return errors.New("minisign signature verification failed")
	}
	return nil
}

// VerifyFile streams a signed executable through Minisign without loading it
// into memory.
func (v *MinisignVerifier) VerifyFile(path, signature string) error {
	if v == nil {
		return errors.New("minisign verifier is not configured")
	}
	signatureText, err := decodeSignature(signature)
	if err != nil {
		return err
	}
	file, err := os.Open(filepath.Clean(path))
	if err != nil {
		return fmt.Errorf("open signed file: %w", err)
	}
	defer file.Close()
	reader := minisign.NewReader(file)
	if _, err := io.Copy(io.Discard, reader); err != nil {
		return fmt.Errorf("read signed file: %w", err)
	}
	if !reader.Verify(v.public, signatureText) {
		return errors.New("minisign signature verification failed")
	}
	return nil
}

func decodeSignature(value string) ([]byte, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil, errors.New("minisign signature is empty")
	}
	decoded, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		return nil, errors.New("minisign signature is not valid base64")
	}
	if len(decoded) == 0 {
		return nil, errors.New("minisign signature is empty")
	}
	return decoded, nil
}

// LoadSignedManifestVerifier loads the direct key first and then the explicit
// key file. A missing key is allowed in development so an unconfigured server
// can return a clear unavailable status instead of exposing an update.
func LoadSignedManifestVerifier(publicKey, publicKeyFile string) (SignedManifestVerifier, error) {
	publicKey = strings.TrimSpace(publicKey)
	publicKeyFile = strings.TrimSpace(publicKeyFile)
	var directErr error
	if publicKey != "" {
		verifier, err := NewMinisignVerifier(publicKey)
		if err == nil {
			return verifier, nil
		}
		directErr = err
	}
	if publicKeyFile != "" {
		cleanPath := filepath.Clean(publicKeyFile)
		contents, err := os.ReadFile(cleanPath)
		if err != nil {
			if directErr != nil {
				return nil, fmt.Errorf("direct update signing public key is invalid (%v); read fallback key file %q: %w", directErr, cleanPath, err)
			}
			return nil, fmt.Errorf("read update signing public key file: %w", err)
		}
		verifier, err := NewMinisignVerifier(string(contents))
		if err != nil {
			if directErr != nil {
				return nil, fmt.Errorf("direct update signing public key is invalid (%v); parse fallback key file %q: %w", directErr, cleanPath, err)
			}
			return nil, fmt.Errorf("parse update signing public key file %q: %w", cleanPath, err)
		}
		return verifier, nil
	}
	if directErr != nil {
		return nil, directErr
	}
	return nil, nil
}

// DecodeSignedClientPayload decodes and verifies client-update.json. Both the
// envelope and signed payload reject duplicate keys, unknown fields, and
// trailing JSON so an attacker cannot exploit parser differentials.
func DecodeSignedClientPayload(envelope *SignedClientUpdateManifest, verifier SignedManifestVerifier) (*ClientUpdatePayload, error) {
	if envelope == nil {
		return nil, errors.New("client update manifest is nil")
	}
	if verifier == nil {
		return nil, errors.New("client update signing public key is not configured")
	}
	if err := validateEnvelope(envelope); err != nil {
		return nil, err
	}
	raw, err := decodePayload(envelope.Payload)
	if err != nil {
		return nil, fmt.Errorf("decode signed client payload: %w", err)
	}
	if err := verifier.Verify(raw, envelope.Signature); err != nil {
		return nil, fmt.Errorf("verify signed client payload: %w", err)
	}
	if err := jsonstrict.RejectDuplicateKeys(raw); err != nil {
		return nil, fmt.Errorf("decode client update payload: %w", err)
	}
	var payload ClientUpdatePayload
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&payload); err != nil {
		return nil, fmt.Errorf("decode client update payload: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return nil, errors.New("decode client update payload: trailing JSON content is not allowed")
	}
	if err := validateClientUpdatePayload(&payload); err != nil {
		return nil, err
	}
	return &payload, nil
}

func validateEnvelope(envelope *SignedClientUpdateManifest) error {
	if strings.TrimSpace(envelope.Payload) == "" {
		return errors.New("signed client payload is empty")
	}
	if strings.TrimSpace(envelope.Signature) == "" {
		return errors.New("signed client manifest signature is empty")
	}
	if _, err := decodePayload(envelope.Payload); err != nil {
		return fmt.Errorf("decode signed client payload: %w", err)
	}
	if _, err := decodeSignature(envelope.Signature); err != nil {
		return fmt.Errorf("decode signed client manifest: %w", err)
	}
	return nil
}

func decodePayload(value string) ([]byte, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil, errors.New("signed payload is empty")
	}
	decoded, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		decoded, err = base64.RawStdEncoding.DecodeString(value)
	}
	if err != nil || len(decoded) == 0 {
		return nil, errors.New("signed payload is not valid base64")
	}
	return decoded, nil
}

func validateClientUpdatePayload(payload *ClientUpdatePayload) error {
	if payload == nil {
		return errors.New("client update payload is nil")
	}
	if normalizeVersion(payload.Version) == "" {
		return errors.New("client update payload version is invalid")
	}
	if payload.Target != clientTargetWindowsX64 {
		return fmt.Errorf("unsupported client update target %q", payload.Target)
	}
	if err := validateClientArtifact(payload.Artifact); err != nil {
		return fmt.Errorf("invalid portable artifact: %w", err)
	}
	return nil
}

func validateClientArtifact(artifact ClientArtifact) error {
	if artifact.Kind != clientArtifactKindPortable {
		return fmt.Errorf("kind must be %q", clientArtifactKindPortable)
	}
	if artifact.Size <= 0 || !isSHA256(artifact.SHA256) || strings.TrimSpace(artifact.Signature) == "" {
		return errors.New("portable artifact requires positive size, sha256 and signature")
	}
	if _, err := decodeSignature(artifact.Signature); err != nil {
		return err
	}
	return nil
}

func isSHA256(value string) bool {
	if len(value) != sha256HexLength {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}

func fileSHA256(path string) (string, int64, error) {
	file, err := os.Open(filepath.Clean(path))
	if err != nil {
		return "", 0, err
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil {
		return "", 0, err
	}
	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", 0, err
	}
	return hex.EncodeToString(hash.Sum(nil)), info.Size(), nil
}

func normalizeVersion(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if !strings.HasPrefix(value, "v") {
		value = "v" + value
	}
	if !semver.IsValid(value) {
		return ""
	}
	return value
}

// CompareVersions compares strict SemVer values and returns -1/0/1. Invalid
// versions are ordered below valid versions, while two invalid values compare
// equal; callers validate external versions before allowing an update.
func CompareVersions(left, right string) int {
	left, right = normalizeVersion(left), normalizeVersion(right)
	if left == right {
		return 0
	}
	if left == "" {
		return -1
	}
	if right == "" || semver.Compare(left, right) > 0 {
		return 1
	}
	return -1
}
