<template>
  <div class="data-page department-page">
    <PageHeader title="部门" description="维护部门状态和成员关系；同一员工可以加入多个部门。" :readonly="!canWrite" @back="switchModule('dashboard')"><template #actions><el-button v-if="canWrite" type="primary" @click="state.openCreate">＋ 新增部门</el-button></template></PageHeader>
    <el-alert v-if="canWrite && !canManageMembers" title="当前账号缺少员工档案查看权限，不能管理部门成员；部门基础信息仍可维护。" type="info" :closable="false" show-icon />
    <PageState v-if="state.error.value && !state.departments.value.length" kind="error" title="部门加载失败" :description="state.error.value" action-label="重新加载" @action="state.load" />
    <el-alert v-else-if="state.error.value" :title="state.error.value" type="error" :closable="false" show-icon><template #default><el-button link type="primary" @click="state.load">重新加载</el-button></template></el-alert>
    <DataTableShell v-else :loading="state.loading.value" :rows-count="state.departments.value.length" :total="state.departments.value.length" :page="1" :page-size="200" empty-title="还没有部门" empty-description="新增部门后，可以配置员工和账号归属。" @retry="state.load">
      <div class="responsive-table-desktop"><el-table :data="state.departments.value" row-key="id" stripe><el-table-column label="部门" min-width="200"><template #default="{row}"><span class="item-name">{{ row.name }}</span><small class="item-code">{{ row.code }}</small></template></el-table-column><el-table-column label="在职员工" width="120"><template #default="{row}">{{ row.employee_count || 0 }} 人</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><StatusTag :label="row.status === 'disabled' ? '已停用' : '启用'" :tone="row.status === 'disabled' ? 'info' : 'success'" /></template></el-table-column><el-table-column v-if="canWrite" label="操作" min-width="260" fixed="right"><template #default="{row}"><el-button link type="primary" :disabled="statusUpdatingID === row.id" @click="state.openEdit(row)">编辑</el-button><el-button link type="primary" :disabled="!canManageMembers || statusUpdatingID === row.id" :title="canManageMembers ? '' : '需要员工档案查看权限'" @click="state.openMembers(row)">管理员工</el-button><el-button link :type="row.status === 'disabled' ? 'success' : 'danger'" :loading="statusUpdatingID === row.id" :disabled="statusUpdatingID !== null && statusUpdatingID !== row.id" @click="toggleStatus(row)">{{ row.status === 'disabled' ? '启用' : '停用' }}</el-button></template></el-table-column></el-table></div>
      <div class="responsive-card-list"><article v-for="row in state.departments.value" :key="row.id" class="department-card"><div class="responsive-card-heading"><div><strong>{{ row.name }}</strong><small>{{ row.code }}</small></div><StatusTag :label="row.status === 'disabled' ? '已停用' : '启用'" :tone="row.status === 'disabled' ? 'info' : 'success'" /></div><p>在职员工 {{ row.employee_count || 0 }} 人</p><div v-if="canWrite" class="card-actions"><el-button :disabled="statusUpdatingID === row.id" @click="state.openEdit(row)">编辑</el-button><el-button :disabled="!canManageMembers || statusUpdatingID === row.id" :title="canManageMembers ? '' : '需要员工档案查看权限'" @click="state.openMembers(row)">管理员工</el-button><el-button :type="row.status === 'disabled' ? 'success' : 'danger'" plain :loading="statusUpdatingID === row.id" :disabled="statusUpdatingID !== null && statusUpdatingID !== row.id" @click="toggleStatus(row)">{{ row.status === 'disabled' ? '启用' : '停用' }}</el-button></div></article></div>
    </DataTableShell>
    <el-drawer v-model="state.formVisible.value" class="business-form-drawer" :title="state.editing.value ? '编辑部门' : '新增部门'" size="min(520px, 100%)" :close-on-click-modal="!state.saving.value" :close-on-press-escape="!state.saving.value" :before-close="requestDepartmentClose"><el-form label-position="top" :disabled="state.saving.value" @submit.prevent="saveDepartment"><el-alert v-if="state.saveError.value" :title="state.saveError.value" type="error" :closable="false" show-icon/><el-form-item label="部门名称" required><el-input v-model.trim="state.form.name" /></el-form-item><el-form-item label="部门编码" required><el-input v-model.trim="state.form.code" /></el-form-item><div class="form-actions drawer-sticky-actions"><el-button :disabled="state.saving.value" @click="requestDepartmentClose()">取消</el-button><el-button type="primary" native-type="submit" :loading="state.saving.value">保存</el-button></div></el-form></el-drawer>
    <DepartmentEmployeesDrawer v-model="state.memberVisible.value" :department="state.memberDepartment.value" :employees="state.employees.value" v-model:selectedEmployeeIDs="state.selectedEmployeeIDs.value" :original-employee-i-ds="state.originalEmployeeIDs.value" v-model:keyword="state.memberKeyword.value" :loading="state.memberLoading.value" :saving="state.saving.value" :load-error="state.memberLoadError.value" :save-error="state.saveError.value" @retry="state.loadMembers()" @save="state.saveMembers" />
  </div>
</template>
<script setup lang="ts">
import {onMounted, ref} from 'vue'
import {ElMessage} from 'element-plus'
import {appMessageBox} from '../../composables/useAppMessageBox'
import {useDepartments} from '../../composables/useDepartments'
import {useWorkspaceContext} from '../../composables/workspaceContext'
import type {DepartmentItem} from '../../types'
import DataTableShell from '../ui/DataTableShell.vue'; import PageHeader from '../ui/PageHeader.vue'; import PageState from '../ui/PageState.vue'; import StatusTag from '../ui/StatusTag.vue'; import DepartmentEmployeesDrawer from './DepartmentEmployeesDrawer.vue'
const {token, hasPermission, switchModule, loadList} = useWorkspaceContext(); const canWrite = hasPermission('system:departments:write'); const canManageMembers = canWrite && hasPermission('system:employees:read'); const state = useDepartments(token); const statusUpdatingID = ref<number | null>(null); onMounted(() => void state.load())
async function saveDepartment() { await state.save(); if (!state.saveError.value) await loadList('departments', false) }
async function requestDepartmentClose(done?: () => void) { if (state.saving.value) return; const original = state.editing.value ? {name: state.editing.value.name, code: state.editing.value.code || ''} : {name: '', code: ''}; const dirty = state.form.name !== original.name || state.form.code !== original.code; if (dirty) { try { await appMessageBox.confirm('部门信息尚未保存，确认关闭？', '放弃修改', {type: 'warning'}) } catch { return } } if (done) done(); else state.formVisible.value = false }
async function toggleStatus(item: any) { if (statusUpdatingID.value !== null) return; const next = item.status === 'disabled' ? 'active' : 'disabled'; try { await appMessageBox.confirm(next === 'disabled' ? `停用部门“${item.name}”？该部门账号将不能执行任务和库存写入。` : `重新启用部门“${item.name}”？`, next === 'disabled' ? '确认停用' : '确认启用', {type: next === 'disabled' ? 'warning' : 'success', confirmButtonText: next === 'disabled' ? '确认停用' : '确认启用', confirmButtonClass: next === 'disabled' ? 'el-button--danger' : ''}); statusUpdatingID.value = Number(item.id); await state.setStatus(item, next); await loadList('departments', false); ElMessage.success('部门状态已更新') } catch (cause) { if (cause instanceof Error) ElMessage.error(cause.message) } finally { statusUpdatingID.value = null } }
</script>
