<template>
  <section class="login-screen" aria-label="博邦光电登录">
      <div class="login-layout">
        <aside class="login-welcome" aria-labelledby="login-welcome-title">
          <img class="login-logo" src="/bobang-logo-hd.png" alt="博邦光电"/>
          <div class="login-welcome__copy">
            <span class="login-eyebrow">博邦 ERP · 业务协同平台</span>
            <h1 id="login-welcome-title">让库存、任务与模具状态清晰可见</h1>
            <p>面向办公室与部门终端的统一工作台，帮助团队快速完成日常业务办理与进度核对。</p>
          </div>
          <ul class="login-capabilities" aria-label="平台能力">
            <li><strong>统一入口</strong><span>按账号权限呈现可用业务</span></li>
            <li><strong>状态明确</strong><span>集中查看库存预警与任务进度</span></li>
            <li><strong>内网友好</strong><span>桌面端可连接企业内网服务</span></li>
          </ul>
        </aside>

        <div class="login-panel">
          <header class="login-panel__heading">
            <span class="login-eyebrow">账号登录</span>
            <h2>登录业务工作台</h2>
            <p>{{ desktopClient ? '使用当前服务器中的账号继续。' : '请输入由管理员分配的账号和密码。' }}</p>
          </header>
          <el-form class="login-form" label-position="top" aria-label="账号登录表单" :aria-busy="loading" @submit.prevent="login">
            <el-form-item label="账号">
              <el-input ref="loginUsernameInput" v-model.trim="loginForm.username" autocomplete="username" autofocus clearable :disabled="loading || serverTesting" placeholder="请输入账号"/>
            </el-form-item>
            <el-form-item label="密码">
              <el-input v-model="loginForm.password" type="password" autocomplete="current-password" show-password :disabled="loading || serverTesting" placeholder="请输入密码"/>
            </el-form-item>
            <el-button class="login-submit" type="primary" :loading="loading" :disabled="loading || serverTesting" native-type="submit">
              {{ loading ? '正在登录' : '登录' }}
            </el-button>
            <el-alert v-if="errorMessage" :title="errorMessage" type="error" :closable="false" show-icon/>
          </el-form>

          <section v-if="desktopClient" class="server-settings login-server-settings" aria-labelledby="login-server-title">
            <div class="server-settings-heading">
              <div>
                <span id="login-server-title">桌面端服务器</span>
                <small>连接运行并分发更新的内网服务器</small>
              </div>
              <StatusTag label="仅桌面端" tone="info"/>
            </div>
            <el-input v-model.trim="serverUrlInput" aria-label="ERP 服务器地址" placeholder="例如 http://192.168.1.20:8080" clearable :disabled="loading || serverTesting"/>
            <small>连接失败时请核对 IP 和端口，并确认处于同一局域网、防火墙已放行且 Go 服务正在运行。</small>
            <div class="server-actions">
              <el-button :loading="serverTesting" :disabled="loading || serverTesting" @click="testServerSetting">测试连接</el-button>
              <el-button type="primary" plain :disabled="loading || serverTesting" @click="saveServerSetting">保存地址</el-button>
            </div>
            <el-alert v-if="serverMessage" :title="serverMessage" :type="serverMessageType" :closable="false" show-icon/>
          </section>
          <p v-else class="login-web-note">Web 版会连接当前站点所配置的服务地址；如无法登录，请联系系统管理员。</p>
        </div>
      </div>
    </section>
</template>

<script setup lang="ts">
import StatusTag from '../ui/StatusTag.vue'
import {useWorkspaceContext} from '../../composables/workspaceContext'

const {
  assignmentConfigs,
  tokenKey,
  desktopClient,
  authRequestGeneration,
  token,
  currentUser,
  activeKey,
  showCreateForm,
  editingSupplier,
  rows,
  columns,
  skeletonResult,
  searchKeyword,
  page,
  pageSize,
  pageTotal,
  loading,
  errorMessage,
  panelMessage,
  listError,
  assignmentTarget,
  assignmentModuleKey,
  selectedAssignmentIDs,
  assignmentOptionsCache,
  assignmentOptionsLoading,
  assignmentOptionsError,
  assignmentSaving,
  assignmentSaveError,
  selectedWarehouseItem,
  warehouseDrawerVisible,
  warehouseDetail,
  warehouseDetailLoading,
  warehouseDetailError,
  itemMovements,
  itemMovementsLoading,
  itemMovementsError,
  showAllItemMovements,
  movementMode,
  showQuickSupplier,
  movementSubmitting,
  movementFormError,
  quickSupplierSubmitting,
  quickSupplierError,
  healthStatus,
  mobileNavOpen,
  serverDialogVisible,
  serverTesting,
  serverUrlInput,
  serverMessage,
  serverMessageType,
  clientUpdate,
  loginForm,
  loginUsernameInput,
  formError,
  formState,
  movementForm,
  quickSupplier,
  activeWarehouseTab,
  workorderStatusFilter,
  workorderTypeFilter,
  workorderPriorityFilter,
  selectedWorkOrder,
  workorderDrawerVisible,
  workorderLogs,
  workorderLogsLoading,
  workorderLogsError,
  moldDetailDrawerVisible,
  selectedMoldDetail,
  selectedMoldID,
  moldDetailLoading,
  moldDetailError,
  moldActionSubmitting,
  moldActionError,
  statisticsData,
  selectedMoldMaintenanceState,
  selectedMoldAlertType,
  warehouseTabs,
  warehouseTabOptions,
  movementDefinitions,
  workorderStatusOptions,
  workorderTypeOptions,
  workorderPriorityOptions,
  navItems,
  businessItems,
  systemItems,
  activeModule,
  canWriteActive,
  activePageReadonly,
  hasActiveFilters,
  filteredEmptyTitle,
  filteredEmptyDescription,
  isMasterDataValidationPage,
  hasRenderableData,
  listSearchPlaceholder,
  masterDataEmptyTitle,
  masterDataEmptyDescription,
  genericIdentityColumns,
  genericStatusColumn,
  genericCardColumns,
  hasAssignmentAction,
  assignmentConfig,
  assignmentOptions,
  assignmentOptionsReady,
  assignmentOptionGroups,
  userInitial,
  greeting,
  quickActionDefinitions,
  quickActions,
  businessGroups,
  accountTypeText,
  healthStatusLabel,
  dashboardMetricCards,
  dashboardFocusItems,
  availableMovementDefinitions,
  movementDependencyMessage,
  movementTitle,
  movementIsOutbound,
  expectedStockQuantity,
  warehouseQuantityAvailable,
  selectedWarehouseStockState,
  selectedWarehouseAlertType,
  movementQuantityError,
  movementCounterpartyLabel,
  formatMovementInputQuantity,
  movementCanSubmit,
  movementSubmitLabel,
  movementFormDirty,
  displayedItemMovements,
  eligibleOriginalDocuments,
  warehouseSummaryCards,
  workorderSummaryCards,
  moldSummaryCards,
  operationalSummaryCards,
  statisticsCards,
  compactTrendItems,
  formSchema,
  cache,
  activeWarehouseTabTitle,
  createEntityTitle,
  rowsFor,
  isPaginatedResponse,
  appendQuery,
  hasPermission,
  canReadModule,
  canWriteModule,
  switchModule,
  selectMobileModule,
  restoreMobileMenuFocus,
  handleUserCommand,
  resetFilters,
  assignmentOptionsRequestToken,
  openAssignment,
  closeAssignment,
  loadAssignmentOptions,
  retryAssignmentOptions,
  isAssignmentOptionDisabled,
  saveAssignment,
  switchWarehouseTab,
  resetListQuery,
  applySearch,
  handlePageChange,
  handlePageSizeChange,
  login,
  clearAuthSession,
  logout,
  openServerSettings,
  testServerSetting,
  saveServerSetting,
  bootstrap,
  loadHealth,
  loadMe,
  loadClientUpdate,
  downloadClientUpdate,
  preloadBaseData,
  loadActiveModule,
  loadStatistics,
  loadList,
  createItem,
  normalizedForm,
  validateActiveForm,
  numericKeys,
  clearForm,
  toggleCreateForm,
  editSupplier,
  inferColumns,
  formatCell,
  genericStatusLabel,
  genericStatusTone,
  isGenericStatusColumn,
  formatGenericCell,
  permissionDomainKey,
  permissionDomainLabel,
  genericRowTitle,
  genericRowSubtitle,
  stockState,
  columnLabels,
  columnLabel,
  warehouseDetailRequestToken,
  itemMovementsRequestToken,
  moldDetailRequestToken,
  workorderLogsRequestToken,
  warehouseDetailAbortController,
  itemMovementsAbortController,
  moldDetailAbortController,
  workorderLogsAbortController,
  invalidateWarehouseRequests,
  isCurrentWarehouseRequest,
  openWarehouseItem,
  warehouseCloseBypass,
  closeWarehouseItem,
  performWarehouseClose,
  requestWarehouseClose,
  handleWarehouseBeforeClose,
  resetWarehouseItem,
  invalidateMoldDetailRequest,
  isCurrentMoldDetailRequest,
  openMold,
  loadMoldDetail,
  closeMold,
  handleMoldBeforeClose,
  resetMold,
  loanMold,
  returnMold,
  repairMold,
  maintainMold,
  runMoldAction,
  loadWarehouseItemDetail,
  loadItemMovements,
  loadAllItemMovements,
  startMovement,
  cancelMovement,
  resetMovementSource,
  clearMovementForm,
  submitMovement,
  createQuickSupplier,
  decimalToScaled,
  moneyToCents,
  formatQuantity,
  formatMoney,
  formatDate,
  businessTypeLabel,
  movementQuantity,
  openWorkOrder,
  invalidateWorkOrderLogsRequest,
  isCurrentWorkOrderLogsRequest,
  closeWorkOrder,
  handleWorkOrderBeforeClose,
  resetWorkOrder,
  loadWorkOrderLogs,
  dispatchWorkOrder,
  pauseWorkOrder,
  resumeWorkOrder,
  toggleWorkOrderUrgent,
  completeWorkOrder,
  startDepartmentTask,
  partialCompleteDepartmentTask,
  completeDepartmentTask,
  runWorkOrderAction,
  promptText,
  promptTextWithDefault,
  promptPositiveInteger,
  departmentTasks,
  departmentProgressMetrics,
  departmentProgressSummary,
  departmentName,
  canOperateDepartmentTask,
  workorderStatusLabel,
  workorderTypeLabel,
  inventoryItemTypeLabel,
  moldStatusLabel,
  moldStatusTone,
  moldMaintenanceState,
  departmentCompletionRate,
  trendNameLabel,
  trendBarPercentage,
  departmentTaskStatusLabel,
  workorderStatusTone,
  workorderDueState,
  departmentTaskStatusTone,
  workorderNextAction,
  workorderActionLabel,
} = useWorkspaceContext()
</script>
