import assert from 'node:assert/strict'
import test from 'node:test'
import {readFileSync} from 'node:fs'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('ResponsiveDetailCarrier 默认右侧停靠，统一正文滚动与72/24/72结构', () => {
  const carrier = read('../src/components/ui/ResponsiveDetailCarrier.vue')
  const panel = read('../src/composables/useResponsiveDetailPanel.ts')
  const shell = read('../src/styles/shell.css')
  const workspace = read('../src/components/app/AppWorkspace.vue')
  const settings = read('../src/components/app/SettingsPanel.vue')
  const styles = read('../src/styles/workspace-components.css')
  assert.match(carrier, /min-height: 72px/)
  assert.match(carrier, /padding: 24px 24px calc\(24px \+ env\(safe-area-inset-bottom/)
  assert.match(carrier, /modal-class="workspace-detail-overlay"/)
  assert.match(carrier, /<Teleport v-if="preferDocked"/)
  assert.match(carrier, /preferDocked: true/)
  assert.match(carrier, /:show-close="showClose && closeOnPressEscape"/)
  assert.match(carrier, /v-if="showClose && closeOnPressEscape" circle/)
  assert.match(panel, /calc\(100vw - 32px\)/)
  assert.match(shell, /\.workspace\.has-docked-detail[^}]*grid-template-columns: minmax\(0, 1fr\) var\(--bb-detail-panel-width\)/)
  assert.match(shell, /\.workspace-detail-host \{ grid-column: 2; \}/)
  assert.match(shell, /\.workspace\.compact-dock-navigation\.has-docked-detail/)
  assert.match(shell, /\.workspace\.compact-dock-navigation\.has-docked-detail \.sidebar \{ border: 0; padding-inline: 0; opacity: 0; pointer-events: none; \}/)
  assert.match(workspace, /Math\.min\(activeDetailWidth\.value, viewportWidth\.value\)/)
  assert.match(workspace, /isNarrow\.value \|\| compactDockNavigationHidden\.value/)
  assert.match(workspace, /usesOverlayNavigation\.value/)
  assert.match(shell, /\.workspace\.compact-dock-navigation\.has-docked-detail \.sidebar\.is-mobile-open/)
  assert.match(shell, /\.workspace\.compact-dock-navigation \.mobile-nav-backdrop/)
  assert.match(workspace, /viewportWidth\.value - activeDetailWidth\.value - configuredSidebarWidth\.value < 720/)
  assert.match(settings, /docked-auto-focus="panel"/)
  assert.match(styles, /rgba\(19, 31, 45, \.26\)/)
  assert.match(styles, /margin-right: 16px/)
  assert.match(styles, /\.el-drawer\.unified-detail > \.el-drawer__body[^}]*padding: 0/)
  assert.match(styles, /\.el-drawer\.unified-detail > \.el-drawer__footer[^}]*padding: 0/)
  assert.match(styles, /\.el-drawer\.unified-detail > \.el-drawer__body > \.detail-body[^}]*overflow-y: auto/)
  assert.doesNotMatch(carrier, /detail-footer > \* \{ flex: 1/)
})

test('面板复杂度明确区分420详情、420短表单和520标准表单', () => {
  const panel = read('../src/composables/useResponsiveDetailPanel.ts')
  const department = read('../src/components/pages/DepartmentPage.vue')
  const moduleForm = read('../src/components/pages/module/ModuleCreateForm.vue')
  const customer = read('../src/components/pages/CustomerProfileDrawer.vue')
  assert.match(panel, /'short-form'/)
  assert.match(panel, /'standard-form'/)
  assert.match(panel, /complexity === 'standard-form'/)
  assert.match(department, /complexity: 'short-form'/)
  assert.match(moduleForm, /complexity: 'standard-form'/)
  assert.match(customer, /complexity: 'standard-form'/)
})

test('表单内容使用共享分组组件，用户个人账号不显示归属字段', () => {
  const moduleForm = read('../src/components/pages/module/ModuleCreateForm.vue')
  const department = read('../src/components/pages/DepartmentPage.vue')
  const customer = read('../src/components/pages/CustomerProfileDrawer.vue')
  assert.match(moduleForm, /<FormPanelContent>/)
  assert.match(moduleForm, /账号信息/)
  assert.match(moduleForm, /归属信息/)
  assert.match(moduleForm, /formState\.account_type === 'department_terminal'/)
  assert.match(department, /<FormSection title="部门信息"/)
  assert.match(customer, /<FormSection title="基本资料"/)
})

test('设置和权限配置使用语义分组、搜索和可读底栏', () => {
  const settings = read('../src/components/app/SettingsPanel.vue')
  const assignment = read('../src/components/pages/module/ModuleAssignmentDialogs.vue')
  assert.match(settings, /<FormSection title="外观"/)
  assert.match(settings, /v-if="currentServer\?\.server_version"/)
  assert.match(settings, /theme-mode-switch/)
  assert.match(settings, /var\(--bb-accent-swatch-bobbang\)/)
  assert.match(assignment, /assignment-search/)
  assert.match(assignment, /全选可配置/)
  assert.match(assignment, /清空可配置/)
  assert.match(assignment, /indeterminate/)
  assert.match(assignment, /assignment-group-toggle/)
  assert.match(assignment, /visibleItems/)
  assert.match(assignment, /assignmentExpansionInitializedFor/)
  assert.match(assignment, /assignment-selection-toolbar" aria-label="批量选择" :aria-busy="assignmentOptionsLoading"/)
  assert.doesNotMatch(assignment, /v-if="assignmentOptionsReady" class="assignment-selection-toolbar"/)
  assert.match(assignment, /width: 40px/)
  assert.match(assignment, /@click\.stop/)
  assert.match(assignment, /保存 \{\{ selectedAssignmentIDs.length \}\} 项/)
  assert.match(assignment, /min-height: 40px/)
  assert.match(assignment, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(assignment, /@container assignment-panel/)
  assert.match(assignment, /gap: 0/)
  assert.match(assignment, /assignment-mobile-dirty/)
  assert.match(assignment, /assignmentOptionDisabledReason\(option\)/)
})

test('权限选项接口独立于导航模块，仍保留角色配置加载路径', () => {
  const modules = read('../src/data/modules.ts')
  const assignment = read('../src/composables/useAssignment.ts')
  const controller = read('../src/composables/useWorkspaceController.ts')
  assert.doesNotMatch(modules, /key: 'permissions'/)
  assert.match(assignment, /optionsPath: '\/api\/v1\/system\/permissions'/)
  assert.match(controller, /appendQuery\(config\.optionsPath/)
  assert.match(controller, /const cachedOptions = config \? assignmentOptionsCache\[config\.optionKey\] : undefined/)
  assert.doesNotMatch(controller, /Object\.prototype\.hasOwnProperty\.call\(assignmentOptionsCache/)
  assert.doesNotMatch(controller, /modules\.find\(\(item\) => item\.key === config\.optionKey\)/)
})

test('客户详情切换编辑不通过key销毁carrier，权限切换等待详情关闭', () => {
  const customer = read('../src/components/pages/CustomerProfileDrawer.vue')
  const generic = read('../src/components/pages/module/GenericModuleContent.vue')
  assert.doesNotMatch(customer, /:key="`\$\{mode-/)
  assert.match(generic, /@closed="resolveDetailClosed"/)
  assert.match(generic, /await closeDetailPanel\(\)/)
})
