import assert from 'node:assert/strict'
import test from 'node:test'
import {readFileSync} from 'node:fs'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('客户与模具导入导出使用固定前端注册表', () => {
  const registry = read('../src/data/transferRegistry.ts')
  assert.match(registry, /export const transferRegistry/)
  assert.match(registry, /path: '\/api\/v1\/customers\/import-template'/)
  assert.match(registry, /fileName: '客户资料导入模板\.xlsx'/)
  assert.match(registry, /path: '\/api\/v1\/customers\/export'/)
  assert.match(registry, /previewPath: '\/api\/v1\/customers\/export\/preview'/)
  assert.match(registry, /fileName: '客户资料\.xlsx'/)
  assert.match(registry, /path: '\/api\/v1\/molds\/import-template'/)
  assert.match(registry, /fileName: '博邦模具导入模板\.zip'/)
  assert.match(registry, /path: '\/api\/v1\/molds\/export'/)
  assert.match(registry, /fileName: '博邦模具资料包\.zip'/)
  assert.match(registry, /permission: 'mold:import'/)
  assert.match(registry, /accept: '\.zip,application\/zip'/)
  assert.match(registry, /rootFiles: Object\.freeze\(\['molds\.xlsx', 'locations\.json'\]\)/)
  assert.match(registry, /'images\/MOLD-001\/product_material\/'/)
  assert.match(registry, /'drawings\/MOLD-001\/'/)
})

test('客户导入、客户导出和模具资料包都使用共享下载 composable', () => {
  const customerImport = read('../src/components/pages/CustomerImportDialog.vue')
  const customerExport = read('../src/components/pages/CustomerExportDialog.vue')
  const mold = read('../src/components/pages/module/MoldModuleContent.vue')
  const download = read('../src/composables/useTransferDownload.ts')
  assert.match(customerImport, /useTransferDownload/)
  assert.match(customerImport, /downloadTransfer\('customers', 'template'\)/)
  assert.match(customerExport, /useTransferDownload/)
  assert.match(customerExport, /downloadTransfer\('customers', 'export', params\)/)
  assert.match(mold, /useTransferDownload/)
  assert.match(mold, /downloadTransfer\('molds', 'template'\)/)
  assert.match(mold, /downloadTransfer\('molds', 'export'\)/)
  assert.match(download, /downloadApiFile\(appendTransferQuery\(definition\.path, query\), definition\.fileName/)
})

test('模具导入窗口提供仅对导入权限可见的 ZIP 模板入口', () => {
  const mold = read('../src/components/pages/module/MoldModuleContent.vue')
  assert.match(mold, /<section v-if="canImport" class="import-template-guide"/)
  assert.match(mold, /\{\{ templateDefinition\.label \}\}/)
  assert.match(mold, /<input v-if="canImport && importDialog" ref="importInput" class="sr-only"[^>]+:accept="importDefinition\.accept"[^>]+tabindex="-1" aria-hidden="true"/)
  assert.match(mold, /仅支持 ZIP 资料包/)
  assert.match(mold, /templateLoading = computed\(\(\) => isTransferLoading\('molds', 'template'\)\)/)
  assert.match(mold, /:close-on-click-modal="!importing && !importPreviewing && !templateLoading"/)
  assert.match(mold, /const canImport = computed\(\(\) => hasPermission\(importDefinition\.permission\)\)/)
  assert.match(mold, /const canRead = computed\(\(\) => hasPermission\(exportDefinition\.permission\)\)/)
  assert.match(mold, /\{\{ importDefinition\.label \}\}/)
  assert.match(mold, /\{\{ templateDefinition\.label \}\}/)
  assert.match(mold, /\{\{ exportDefinition\.label \}\}/)
  assert.match(mold, /const importExtensions = importDefinition\.accept\.split\(/)
  assert.match(mold, /acceptsImportFileName\(file\.name\)/)
  assert.match(mold, /acceptsImportFileName\(path\)/)
  assert.match(mold, /ref="moreActionsButton"/)
  assert.match(mold, /@opened="focusImportDialogEntry"/)
  assert.match(mold, /@closed="restoreImportTriggerFocus"/)
  assert.match(mold, /async function focusImportDialogEntry\(\)/)
  assert.match(mold, /document\.querySelector<HTMLElement>\('\.el-dialog\.mold-import-dialog'\)/)
  assert.match(mold, /async function restoreImportTriggerFocus\(\)/)
})

test('传输失败由共享下载 composable 统一反馈，页面只清理旧的本地错误', () => {
  const customerImport = read('../src/components/pages/CustomerImportDialog.vue')
  const customerExport = read('../src/components/pages/CustomerExportDialog.vue')
  const mold = read('../src/components/pages/module/MoldModuleContent.vue')
  const download = read('../src/composables/useTransferDownload.ts')
  assert.match(download, /ElMessage\.error/)
  assert.match(customerImport, /error\.value = ''\s+try \{ await downloadTransfer\('customers', 'template'\) \}/)
  assert.match(customerImport, /catch \{ \/\* 下载反馈由共享传输 composable 统一负责 \*\/ \}/)
  assert.match(customerExport, /error\.value = ''\s+try \{\s+const params = query\(1\)/)
  assert.match(customerExport, /catch \{ \/\* 下载反馈由共享传输 composable 统一负责 \*\/ \}/)
  assert.match(mold, /async function downloadTemplate\(\) \{ importError\.value = ''; try \{ await downloadTransfer\('molds', 'template'\) \} catch \{ \/\* 下载反馈由共享传输 composable 统一负责 \*\/ \} \}/)
})
