/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavigation: typeof import('./src/components/ui/AppNavigation.vue')['default']
    AppWorkspace: typeof import('./src/components/app/AppWorkspace.vue')['default']
    DashboardPage: typeof import('./src/components/pages/DashboardPage.vue')['default']
    DataTableShell: typeof import('./src/components/ui/DataTableShell.vue')['default']
    DesktopUpdatePanel: typeof import('./src/components/DesktopUpdatePanel.vue')['default']
    DetailPanels: typeof import('./src/components/pages/DetailPanels.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FilterBar: typeof import('./src/components/ui/FilterBar.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    LoginScreen: typeof import('./src/components/app/LoginScreen.vue')['default']
    MetricCard: typeof import('./src/components/ui/MetricCard.vue')['default']
    ModulePage: typeof import('./src/components/pages/ModulePage.vue')['default']
    MoldDrawer: typeof import('./src/components/pages/MoldDrawer.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    PageState: typeof import('./src/components/ui/PageState.vue')['default']
    ServerSettingsDialog: typeof import('./src/components/pages/ServerSettingsDialog.vue')['default']
    StatusTag: typeof import('./src/components/ui/StatusTag.vue')['default']
    UpdateCenter: typeof import('./src/components/UpdateCenter.vue')['default']
    WarehouseDrawer: typeof import('./src/components/pages/WarehouseDrawer.vue')['default']
    WorkorderDrawer: typeof import('./src/components/pages/WorkorderDrawer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
